require 'rspec'
require 'pp'
require 'systemu'

# To run this test:
# $ rspec /path/to/test_script_being_tested.rb

# Assumes that the name of the file being tested is ../something.rb relative to the directory containing this test scripts, and the name of this tes script is test_something.rb
$:.unshift File.join(File.dirname(__FILE__),'..')
script_under_test = File.basename(__FILE__).gsub(/_spec.rb$/,'.rb')
path_to_script = File.join(File.dirname(__FILE__),'..','bin',script_under_test)


describe script_under_test do
  it 'should scripting test ok' do
inputs = <<EOF
AAAAAAAAAATCAACCAAAATGTTCCATCACTTGACAATTTTTGGTTATCGGTTGTATACCTCAAGATTTGCTACTTTGTCAGAAGAGGGGAAAAAAAAGC 36 0 0 18 29 37 32 0 0 41
AAAAAAAAAGACGCCCGTTCACCGGGCGCCTCTTGTTGTGAAATGAATTATCTCCGATGGTTCGTTATCTGATCGCCTCTTCGGTCTCGGCATCGAAGATG 0 0 0 0 0 0 0 0 0 0
AAAAAAAAAGATCTCAGCCTCTAAGAAACGAAAACATGGTCTCTCTCAATCCATAACGTCGCCTGTTGATCGCGTTCTGTTACTTCAAAGAACCTTCGGCA 0 0 0 0 0 0 0 0 0 0
AAAAAAAAATCAACCAAAATGTTCCATCACTTGACAATTTTTGGTTATCGGTTGTATACCTCAAGATTTGCTACTTTGTCAGAAGAGGGGAAAAAAAAGCC 2121 0 0 1416 1790 2229 2115 0 1 2399
AAAAAAAAATCAACCAAAATGTTCCATCACTTGACAATTTTTGGTTATCGGTTGTATACCTCAAGATTTGCTACTTTGTCAGAAGAGGGGAAAAAAAGCCA 68 0 0 49 60 94 80 0 0 86
AAAAAAAACAATAGGTTTGTACTCCCGTTAGAGGTGCTGCCACCACGGTGGTTGCTGAGAACACACTCTTGGAACCTGATTCGGATAATGCCGACGAAGGA 0 0 0 0 0 0 0 0 0 0
AAAAAAAACCCAGCAACGGTTACATACGCTCAGAGCAGAAGAAAAAAAAGCATCGCGCTCACTAACGGGTCTTCAACGGCAGCGTCACTCCATCACGCTGT 0 0 0 0 0 0 0 0 0 0
AAAAAAAACCCGAATCAGATGCTGGTACTCAAGGTCTTAAAGACCGTTGTCCTATCAGCAGATAAAAAATCCCATATCAAGCAGAGGATAGAGCACCTCAA 2 0 0 0 0 0 0 0 0 1
AAAAAAAAGACGCCCGTTCACCGGGCGCCTCTTGTTGTGAAATGAATTATCTCCGATGGTTCGTTATCTGATCGCCTCTTCGGTCTCGGCATCGAAGATGT 0 0 0 0 0 0 0 0 0 0
AAAAAAAAGAGAATAGTGATCAAGTTTGATAGTACATCGACGTTTTAGCTGATAGCTTCCTCCAGAAGCTGTCTGCCATAAACCTGCGCATATTCACCGTT 0 0 0 0 0 0 0 0 0 0
EOF

    status, stdout, stderr = systemu "#{path_to_script} --threshold 1000 -", 'stdin' => inputs
    raise stderr if stderr != ''
    stderr.should eq("")
    status.exitstatus.should eq(0), "testing #{path_to_script}"

    expected = (1..632).collect{|s| "#{s}\t"}.join("\n")+
      "\n633\t1\n"
    stdout.should eq(expected)
  end
end
